"""Execution history models.

Import order matters: ``history`` and ``codebase`` reference ``executions`` and
``execution_repos`` by name, so ``execution`` has to register first, and
``codebase`` before ``history`` since the event store inserts code changes.
"""

from .execution import (  # noqa: F401
    LEGAL_TRANSITIONS,
    OID,
    TERMINAL_STATUSES,
    Execution,
    ExecutionComplete,
    ExecutionCreate,
    ExecutionDetail,
    ExecutionError,
    ExecutionFail,
    ExecutionRepoAttach,
    ExecutionRepoHead,
    ExecutionRepoLand,
    ExecutionRepoLink,
    ExecutionRepoResponse,
    ExecutionResponse,
    ExecutionSort,
    ExecutionStatus,
    ExecutionStore,
    ExecutionUsage,
    ExecutorType,
)
from .codebase import (  # noqa: F401
    ChangeType,
    CodeChange,
    CodeChangeCreate,
    CodeChangeResponse,
    CodeDiffApplied,
)
from .history import (  # noqa: F401
    ActorType,
    CodeChangeContext,
    CodeChangeHistoryEntry,
    CodeHistoryStore,
    EventPage,
    EventStore,
    ExecutionEvent,
    ExecutionEventCreate,
    ExecutionEventDetail,
    ExecutionEventPayload,
    ExecutionEventPayloadIn,
    ExecutionEventResponse,
    ExecutionEventType,
    allocate_event_seq,
)
from .interrupts import (  # noqa: F401
    RESOLUTIONS_FOR_KIND,
    WAITING_FOR_KIND,
    ExecutionIntervention,
    InterventionAnswer,
    InterventionDecision,
    InterventionKind,
    InterventionOpen,
    InterventionResponse,
    InterventionStatus,
    InterventionStore,
)

__all__ = [
    "LEGAL_TRANSITIONS",
    "OID",
    "RESOLUTIONS_FOR_KIND",
    "TERMINAL_STATUSES",
    "WAITING_FOR_KIND",
    "ActorType",
    "ChangeType",
    "CodeChange",
    "CodeChangeContext",
    "CodeChangeCreate",
    "CodeChangeHistoryEntry",
    "CodeChangeResponse",
    "CodeDiffApplied",
    "CodeHistoryStore",
    "EventPage",
    "EventStore",
    "Execution",
    "ExecutionComplete",
    "ExecutionCreate",
    "ExecutionDetail",
    "ExecutionError",
    "ExecutionEvent",
    "ExecutionEventCreate",
    "ExecutionEventDetail",
    "ExecutionEventPayload",
    "ExecutionEventPayloadIn",
    "ExecutionEventResponse",
    "ExecutionEventType",
    "ExecutionFail",
    "ExecutionIntervention",
    "ExecutionRepoAttach",
    "ExecutionRepoHead",
    "ExecutionRepoLand",
    "ExecutionRepoLink",
    "ExecutionRepoResponse",
    "ExecutionResponse",
    "ExecutionSort",
    "ExecutionStatus",
    "ExecutionStore",
    "ExecutionUsage",
    "ExecutorType",
    "InterventionAnswer",
    "InterventionDecision",
    "InterventionKind",
    "InterventionOpen",
    "InterventionResponse",
    "InterventionStatus",
    "InterventionStore",
    "allocate_event_seq",
]
