"""executions tables for tasks

Revision ID: 192294ef0add
Revises: e8ded99c469b
Create Date: 2026-08-01 19:04:51.564836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '192294ef0add'
down_revision: Union[str, Sequence[str], None] = 'e8ded99c469b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agents_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('created_by', 'name', name='uq_agents_created_by_name')
    )
    op.create_index(op.f('ix_agents_created_by'), 'agents', ['created_by'], unique=False)
    op.create_table('git_repos',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('remote_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_git_repos_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_repos')),
    sa.UniqueConstraint('created_by', 'name', name='uq_git_repos_created_by_name')
    )
    op.create_index(op.f('ix_git_repos_created_by'), 'git_repos', ['created_by'], unique=False)
    op.create_table('executions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('executor_type', sa.String(length=16), nullable=False),
    sa.Column('executor_user_id', sa.Uuid(), nullable=True),
    sa.Column('executor_agent_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('additional_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_event_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(executor_type = 'human'    AND executor_user_id  IS NOT NULL AND executor_agent_id IS NULL) OR (executor_type = 'ai_agent' AND executor_agent_id IS NOT NULL AND executor_user_id  IS NULL)", name=op.f('ck_executions_executor_matches_type')),
    sa.CheckConstraint("(status = 'failed') = (error IS NOT NULL)", name=op.f('ck_executions_error_matches_status')),
    sa.CheckConstraint("executor_type IN ('human', 'ai_agent')", name=op.f('ck_executions_executor_type')),
    sa.CheckConstraint("status IN ('pending', 'running', 'waiting_approval', 'waiting_input', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_executions_status')),
    sa.CheckConstraint("status NOT IN ('succeeded', 'failed', 'cancelled') OR finished_at IS NOT NULL", name=op.f('ck_executions_terminal_has_finished_at')),
    sa.CheckConstraint('finished_at IS NULL OR (started_at IS NOT NULL AND finished_at >= started_at)', name=op.f('ck_executions_finished_after_started')),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND (cost_usd IS NULL OR cost_usd >= 0)', name=op.f('ck_executions_usage_non_negative')),
    sa.CheckConstraint('last_event_seq >= 0', name=op.f('ck_executions_last_seq_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_executions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['executor_agent_id'], ['agents.id'], name=op.f('fk_executions_executor_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['executor_user_id'], ['users.id'], name=op.f('fk_executions_executor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_executions_task_id_tasks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('task_id', 'attempt', name='uq_executions_task_attempt')
    )
    op.create_index('ix_executions_created_by_created', 'executions', ['created_by', 'created_at'], unique=False)
    op.create_index('ix_executions_task_created', 'executions', ['task_id', 'created_at'], unique=False)
    op.create_table('execution_events',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('cerebral_commit_sha', sa.String(length=64), nullable=True),
    sa.CheckConstraint("(actor_type = 'user') = (actor_user_id IS NOT NULL)", name=op.f('ck_execution_events_user_actor_has_user_id')),
    sa.CheckConstraint("actor_type IN ('agent', 'user', 'system')", name=op.f('ck_execution_events_actor_type')),
    sa.CheckConstraint("event_type IN ('chat_message', 'reasoning', 'decision', 'tool_call', 'tool_result', 'code_change', 'status_change', 'intervention_requested', 'intervention_resolved', 'memory_loaded', 'memory_saved')", name=op.f('ck_execution_events_event_type')),
    sa.CheckConstraint('seq > 0', name=op.f('ck_execution_events_seq_positive')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_execution_events_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_events_execution_id_executions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['execution_events.id'], name=op.f('fk_execution_events_parent_event_id_execution_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('execution_id', 'client_event_id', name='uq_execution_events_client_event_id'),
    sa.UniqueConstraint('execution_id', 'seq', name='uq_execution_events_seq'),
    sa.UniqueConstraint('id', 'execution_id', name='uq_execution_events_id_execution')
    )
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_events_parent_event_id'), 'execution_events', ['parent_event_id'], unique=False)
    op.create_table('execution_repos',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('ref_name', sa.String(length=512), nullable=False),
    sa.Column('base_commit_sha', sa.String(length=64), nullable=False),
    sa.Column('head_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('landed_branch', sa.String(length=255), nullable=True),
    sa.Column('landed_commit_shas', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('merge_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('landed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(landed_at IS NULL) = (jsonb_array_length(landed_commit_shas) = 0)', name=op.f('ck_execution_repos_landed_consistent')),
    sa.CheckConstraint('merge_commit_sha IS NULL OR landed_at IS NOT NULL', name=op.f('ck_execution_repos_merge_implies_landed')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_repos_execution_id_executions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repos.id'], name=op.f('fk_execution_repos_repo_id_git_repos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('execution_id', 'repo_id', name=op.f('pk_execution_repos'))
    )
    op.create_table('code_changes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('previous_path', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('before_blob', sa.String(length=64), nullable=True),
    sa.Column('after_blob', sa.String(length=64), nullable=True),
    sa.Column('landed_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_deleted', sa.Integer(), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reverts_change_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(change_type = 'created'  AND before_blob IS NULL     AND after_blob IS NOT NULL) OR (change_type = 'deleted'  AND before_blob IS NOT NULL AND after_blob IS NULL) OR (change_type IN ('modified','renamed') AND before_blob IS NOT NULL AND after_blob IS NOT NULL)", name=op.f('ck_code_changes_blobs_match_type')),
    sa.CheckConstraint("(change_type = 'renamed') = (previous_path IS NOT NULL)", name=op.f('ck_code_changes_rename_has_previous_path')),
    sa.CheckConstraint("change_type IN ('created', 'modified', 'deleted', 'renamed')", name=op.f('ck_code_changes_change_type')),
    sa.CheckConstraint('lines_added >= 0 AND lines_deleted >= 0', name=op.f('ck_code_changes_line_counts_non_negative')),
    sa.CheckConstraint('reverts_change_id IS NULL OR reverts_change_id <> id', name=op.f('ck_code_changes_revert_not_self')),
    sa.ForeignKeyConstraint(['event_id'], ['execution_events.id'], name=op.f('fk_code_changes_event_id_execution_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id', 'repo_id'], ['execution_repos.execution_id', 'execution_repos.repo_id'], name='fk_code_changes_execution_repo', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_code_changes_execution_id_executions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repos.id'], name=op.f('fk_code_changes_repo_id_git_repos')),
    sa.ForeignKeyConstraint(['reverts_change_id'], ['code_changes.id'], name=op.f('fk_code_changes_reverts_change_id_code_changes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_changes')),
    sa.UniqueConstraint('event_id', 'seq', name='uq_code_changes_event_seq')
    )
    op.create_index(op.f('ix_code_changes_event_id'), 'code_changes', ['event_id'], unique=False)
    op.create_index(op.f('ix_code_changes_execution_id'), 'code_changes', ['execution_id'], unique=False)
    op.create_index(op.f('ix_code_changes_repo_id'), 'code_changes', ['repo_id'], unique=False)
    op.create_index('ix_code_changes_repo_path_created', 'code_changes', ['repo_id', 'path', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('execution_interventions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_event_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(kind = 'input_required' AND status IN ('pending', 'answered', 'expired')) OR (kind IN ('approval', 'qa_review')     AND status IN ('pending', 'approved', 'rejected', 'expired'))", name=op.f('ck_execution_interventions_status_matches_kind')),
    sa.CheckConstraint("(status = 'pending') = (resolved_at IS NULL)", name=op.f('ck_execution_interventions_resolved_at_matches_status')),
    sa.CheckConstraint("kind IN ('approval', 'qa_review', 'input_required')", name=op.f('ck_execution_interventions_kind')),
    sa.CheckConstraint("status <> 'expired' OR expires_at IS NOT NULL", name=op.f('ck_execution_interventions_expired_has_deadline')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'answered', 'expired')", name=op.f('ck_execution_interventions_status')),
    sa.ForeignKeyConstraint(['event_id', 'execution_id'], ['execution_events.id', 'execution_events.execution_id'], name='fk_execution_interventions_event_execution', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_interventions_execution_id_executions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolution_event_id', 'execution_id'], ['execution_events.id', 'execution_events.execution_id'], name='fk_execution_interventions_resolution_event_execution', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_execution_interventions_resolved_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_interventions'))
    )
    op.create_index(op.f('ix_execution_interventions_event_id'), 'execution_interventions', ['event_id'], unique=False)
    op.create_index(op.f('ix_execution_interventions_execution_id'), 'execution_interventions', ['execution_id'], unique=False)
    op.create_index('ix_execution_interventions_pending', 'execution_interventions', ['created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('uq_execution_one_pending_intervention', 'execution_interventions', ['execution_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('uq_execution_one_pending_intervention', table_name='execution_interventions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_execution_interventions_pending', table_name='execution_interventions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_execution_interventions_execution_id'), table_name='execution_interventions')
    op.drop_index(op.f('ix_execution_interventions_event_id'), table_name='execution_interventions')
    op.drop_table('execution_interventions')
    op.drop_index('ix_code_changes_repo_path_created', table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_repo_id'), table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_execution_id'), table_name='code_changes')
    op.drop_index(op.f('ix_code_changes_event_id'), table_name='code_changes')
    op.drop_table('code_changes')
    op.drop_table('execution_repos')
    op.drop_index(op.f('ix_execution_events_parent_event_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index('ix_executions_task_created', table_name='executions')
    op.drop_index('ix_executions_created_by_created', table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_git_repos_created_by'), table_name='git_repos')
    op.drop_table('git_repos')
    op.drop_index(op.f('ix_agents_created_by'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
