"""executions tables for tasks

Revision ID: 5f6528467f14
Revises: 192294ef0add
Create Date: 2026-08-01 19:25:32.198557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5f6528467f14'
down_revision: Union[str, Sequence[str], None] = '192294ef0add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
