"""changes in events repo

Revision ID: 6d2281388768
Revises: a0880f40ca0b
Create Date: 2026-08-09 12:59:38.658862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '6d2281388768'
down_revision: Union[str, Sequence[str], None] = 'a0880f40ca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
