"""history

Revision ID: 7f46ac20493f
Revises: f696390c3f0d
Create Date: 2026-08-09 14:36:25.527428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '7f46ac20493f'
down_revision: Union[str, Sequence[str], None] = 'f696390c3f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
