"""some changes in the repo

Revision ID: a0880f40ca0b
Revises: cbd44698af19
Create Date: 2026-08-09 11:50:59.917376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a0880f40ca0b'
down_revision: Union[str, Sequence[str], None] = 'cbd44698af19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
