"""changes for repos in git repo and agents

Revision ID: cbd44698af19
Revises: f905dc7a4527
Create Date: 2026-08-08 19:54:19.121709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'cbd44698af19'
down_revision: Union[str, Sequence[str], None] = 'f905dc7a4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_git_repos_created_by_local_path', 'git_repos', ['created_by', 'local_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_git_repos_created_by_local_path', table_name='git_repos')
    # ### end Alembic commands ###
