"""added assigned to the task

Revision ID: e8ded99c469b
Revises: 2201aa0c7ad0
Create Date: 2026-07-29 10:03:49.738333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e8ded99c469b"
down_revision: Union[str, Sequence[str], None] = "2201aa0c7ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "assigned_to",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="creator",
        ),
    )
    op.alter_column("tasks", "assigned_to", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "assigned_to")
    # ### end Alembic commands ###
