"""interventations

Revision ID: f696390c3f0d
Revises: 6d2281388768
Create Date: 2026-08-09 13:41:27.495629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f696390c3f0d'
down_revision: Union[str, Sequence[str], None] = '6d2281388768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
