"""api keys

Revision ID: f905dc7a4527
Revises: 5f6528467f14
Create Date: 2026-08-08 19:39:15.876293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.repo.types # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f905dc7a4527'
down_revision: Union[str, Sequence[str], None] = '5f6528467f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name=op.f('ck_api_keys_expires_after_created')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_api_keys_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_agent_id'), 'api_keys', ['agent_id'], unique=False)
    op.create_index(op.f('ix_api_keys_created_by'), 'api_keys', ['created_by'], unique=False)
    op.create_index('ix_api_keys_created_by_active', 'api_keys', ['created_by', 'created_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    op.drop_index(op.f('uq_execution_one_pending_intervention'), table_name='execution_interventions', postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('ix_execution_interventions_execution_pending', 'execution_interventions', ['execution_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_interventions_execution_pending', table_name='execution_interventions', postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('uq_execution_one_pending_intervention'), 'execution_interventions', ['execution_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index('ix_api_keys_created_by_active', table_name='api_keys', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_api_keys_created_by'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_agent_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
